# Theme Settings
title: Basic Theme
logos:
  type: 'svg' # Options include 'wordmark', 'img', and 'svg'
  img: https://placehold.it/150x50
  svg: svg/logo.html
colors:
  primary: '#cc401c'
  primaryDark: '#8f2d15'
  primaryLight: '#cd735b'
  secondary: '#1ccc94'
  secondaryDark: '#007f57'
  secondaryLight: '#5dd4ae'
  grey: '#999'
  greyDark: '#444'
  greyLight: '#f2f2f2'
fonts:
  primary: '"Montserrat", sans-serif'
  secondary: '"Montserrat Alternates", sans-serif;'
transitions:
  primary: '.25s ease-in-out'
header:
  headerStyle: alt # Options include: basic, alt, fancy
nav:
  navItems:
    - text: Home
    - text: Shop
      url: 'shop'
    - text: About
      url: 'about'
    - text: Contact
      url: 'contact'
footer:
  footerStyle: fancy # Options include: basic, alt, fancy

# Pages
home:
  sections: # Options include: banne,r info, text, logos, and cta
    - type: hero
      id: section-1
      bgColor: dark grey
    - type: info
      id: section-2
    - type: text
      id: section-3
    - type: logos
      id: section-4
    - type: cta
      id: section-5
