colors:
  grey: '#999'
  greyDark: '#444'
  greyLight: '#f2f2f2'
  primary: '#f442a1'
  primaryDark: '#8f2d15'
  primaryLight: '#cd735b'
  secondary: '#1ccc94'
  secondaryDark: '#007f57'
  secondaryLight: '#5dd4ae'
